# Generated by Django 3.2.5 on 2021-07-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210709_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='entries',
            field=models.IntegerField(default=0),
        ),
    ]
